### PR TITLE
Nix passed events, update this week's events

### PR DESCRIPTION
**Pull request by rosskukulinski**
I just cleared out this past weeks events and updated this week.  I also fixed a broken link to the README.md

### CODE REVIEW

**Comment by hackygolucky** [comment]
Ah, good catch! :+1:

**Comment by rosskukulinski** [comment]
:-/ about failed build.  I think its because the branch name on _my_ fork is 'master'... does that sound correct?

**Comment by gergelyke** [comment]
It fails, because travis doesn't have access to your repo.

**Comment by gergelyke** [comment]
But looks good, going to merge it. Ok?

**Comment by rosskukulinski** [comment]
gotcha, thanks @gergelyke.  I have no further changes to make.

**Pull request merged**
