### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iancrowther**
Added London nodeschool

### CODE REVIEW

**Comment by iancrowther** [comment]
any ideas why this killed the travis build? it a simple change to the readme to add an event

**Comment by mikeal** [comment]
let's find out, i'll merge it. 

LIVIN ON THE EDGE!

**Comment by mikeal** [comment]
hrm... travis hasn't auto deployed yet, i wonder what is going on.

**Comment by mikeal** [comment]
oh, nope, there it went. everything is Kosher :)

**Comment by iancrowther** [comment]
strange! thanks for diving in..

**Pull request merged**
