### PR TITLE
Update README with JS conferences and knode.io mention

### PR DESCRIPTION
**Pull request by hackygolucky**
This adds some more general JS conferences that have been confirmed for 2014. It also add knode.io as a contribution option for those looking to share more on their local user group.

### CODE REVIEW

**Comment by hackygolucky** [comment]
@mikeal @phated @gergelyke Thoughts? Editing is always welcome and I'm forever in the habit of PR mode. Thanks for input!

**Comment by mikeal** [comment]
we can just remove the comment about this issue tracker being used as a message board, we should just use knode for all that.

also, should run the build script to update the html page :)

**Comment by hackygolucky** [comment]
Updated.

**Comment by phated** [comment]
Didn't verify any dates, but content looks good.

**Pull request merged**
