### PR TITLE
Building the Meatspace

### PR DESCRIPTION
**Pull request by gergelyke**
Added a little pre-commit hook to run the build script, hopefully this way we have a smaller chance to forget it :)
Also, an install script is included using Grunt.

### CODE REVIEW

**Comment by mikeal** [comment]
i don't know anything about grunt so if you wanted a _"review"_ someone else should look at it. but go ahead and merge if you're pretty sure it works :)

**Comment by hackygolucky** [comment]
Yeah, unfortunately I have no experience with grunt. Merge on with your bad
self?

**Comment by rosskukulinski** [comment]
I also have no grunt experience :-/

**Comment by rosskukulinski** [comment]
Hey @gergelyke -  What do you think about adding the modified index.html to the commit with the pre-commit?

I.e.:

```
#!/bin/sh                                                                                                                              
#run script to build html the page                                                                                                     
node build.js
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
    exit 1
fi
git add index.html
```

The upside to this is that if you update the readme, the index.html is automatically built and committed (assuming you've installed grunt and ran 'grunt' in the directory to install the git hooks).  The downside to this is that developers would never see the updated index.html in their working directory -- it would go from unchanged to committed.

**Comment by hackygolucky** [comment]
I like any idea that helps us automate--I was trying to figure out a better
workflow after merging a PR adding an event and having to run the build
script myself.

It is really an automatic process already. I would be concerned at
something going horribly wrong and breaking the site temporarily. Is that
possible?

**Comment by gergelyke** [comment]
@rosskukulinski I think it is a good idea! Sure, it has the downside you mentioned, but the index.html will always reflect the state of the markdown file. I will create another PR, and you can test it out!

**Comment by rosskukulinski** [comment]
valid concerns - but after looking at how the site is generated I'm not that worried.  build.js simply converts the README.md markdown to HTML (and if that conversion fails, the pre-commit hook fails, which keeps you from committing).

@gergelyke I have that exact change in place already, I can submit a PR since I've got it already

**Comment by gergelyke** [comment]
then please do :+1:

**Pull request merged**
