### PR TITLE
Travis added

### PR DESCRIPTION
**Pull request by gergelyke**
After each PR merged, the gh-pages branch will auto-magically will be deployed, no need to run anything manually ;)

### CODE REVIEW

**Comment by hackygolucky** [comment]
Whoa. NICE!

**Comment by gergelyke** [comment]
Thanks, and i am sorry, that there were no issues regarding this, but after i got the idea, i had to do it... i hope all of you like it! :)

**Comment by mikeal** [comment]
i'm gonna move it to knode first :)

**Comment by mikeal** [comment]
swapped the default branch.

**please!** write a blog post about this. there's probably dozen other projects I can think of that would benefit :)

**Comment by hackygolucky** [comment]
+1000

Come to think of it...(looking at the other knode repos now)

**Comment by mikeal** [comment]
even better, turn this in to a module i can run that writes all this shit out for me :)

**Comment by phated** [comment]
@gergelyke can you pop in IRC - #pdxnode?

**Comment by gergelyke** [comment]
A few resources that can be very helpful doing the same: 
- http://awestruct.org/auto-deploy-to-github-pages/
- http://sleepycoders.blogspot.hu/2013/03/sharing-travis-ci-generated-files.html 
- http://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/

**Pull request merged**
