### PR TITLE
Added Thunder Plains Conf Oct 9 2014

### PR DESCRIPTION
**Pull request by amandaharlin**
Hey Knode friends! I added in Thunder Plains Oct 9 2014 Conference. Please let me know if I can modify this pr in any way. Thank you!

### CODE REVIEW

**Comment by hackygolucky** [comment]
Thanks Amanda! Because of the way we have the template build setup, we edit the README.md and the index.html will follow suit. 

Could you make your changes in the README instead?

**Comment by jqtrde** [comment]
Updated the README to include these changes. See [https://github.com/knode/node-meatspace/pull/112](https://github.com/knode/node-meatspace/pull/112).

**Comment by hackygolucky** [comment]
Taken care of with the merge of 91fa8ff
Thanks everyone!

**Comment by amandaharlin** [comment]
Thank you for explaining that, @hackygolucky! I really appreciate it! Also thank you so much @jacquestardie, that was so unexpected and kind!

**Comment by jqtrde** [comment]
no problem @amandaharlin :+1:

**Pull request closed without merging**
